name: macos-qt6

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        target: 'desktop'
        arch: 'clang_64'
        dir: '${{github.workspace}}/qt/'
        modules: qtwebengine qtwebchannel qtpositioning qt5compat
    - name: Install QuaZIP
      run: |
        mkdir -p quazip_1.4
        cd quazip_1.4
        git clone https://github.com/stachenov/quazip.git
        git -C quazip checkout 9d3aa3ee948c1cde5a9f873ecbc3bb229c1182ee
        mkdir 'build'
        mkdir 'installed'
        MACOSX_DEPLOYMENT_TARGET=10.15 cmake -S quazip -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        cmake --build build --config Release 
        cmake --install build --prefix installed
        cd ..
    - name: Install TBB
      run: |
        brew install tbb
    - name: Build
      env:
        CMAKE_PREFIX_PATH: ${{github.workspace}}/quazip_1.4/installed/lib/cmake/QuaZip-Qt6-1.4
      run: |
        cd SlackLogViewer
        mkdir build
        mkdir SlackLogViewer_macos_qt6
        MACOSX_DEPLOYMENT_TARGET=10.15 cmake -S ./ -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=SlackLogViewer_macos_qt6 -DQT_MAJOR_VERSION=6 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        cmake --build build --config Release
        cmake --install build
        tar -c SlackLogViewer_macos_qt6/SlackLogViewer.app | xz -6 > SlackLogViewer_macos_qt6.tar.xz
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: macos-qt6
        path: SlackLogViewer/SlackLogViewer_macos_qt6.tar.xz