name: macos

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        target: 'desktop'
        arch: 'clang_64'
        dir: '${{github.workspace}}/qt/'
        modules: qtwebengine
    - name: Install QuaZIP
      run: |
        mkdir -p quazip_1.4
        cd quazip_1.4
        git clone https://github.com/stachenov/quazip.git
        git -C quazip checkout 9d3aa3ee948c1cde5a9f873ecbc3bb229c1182ee
        mkdir 'build'
        mkdir 'installed'
        MACOSX_DEPLOYMENT_TARGET=10.15 cmake -S quazip -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        cmake --install build --prefix installed
        cd ..
    - name: Install TBB
      run: |
        brew install tbb
    - name: Build
      env:
        CMAKE_PREFIX_PATH: ${{github.workspace}}/quazip_1.4/installed/lib/cmake/QuaZip-Qt5-1.4
      run: |
        cd SlackLogViewer
        mkdir build
        mkdir SlackLogViewer_macos
        MACOSX_DEPLOYMENT_TARGET=10.15 cmake -S ./ -B build -DCMAKE_BUILD_TYPE=Release -DQT_MAJOR_VERSION=5 -DCMAKE_INSTALL_PREFIX=SlackLogViewer_macos
        cmake --build build --config Release
        cmake --install build
        tar -c SlackLogViewer_macos/SlackLogViewer.app | xz -6 > SlackLogViewer_macos.tar.xz
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: SlackLogViewer/SlackLogViewer_macos.tar.xz